name: Deploy to GitHub Pages

on:
  pull_request:
    types: [closed]  # Trigger when a PR is merged
  push:
    branches:
      - staging  # Trigger when commits are pushed to the staging branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (or other environment)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Adjust as per your project's Node version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the site
      - name: Build site
        run: npm run build  # Adjust based on your project's build command

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build